# This file was generated by GoReleaser. DO NOT EDIT.
cask "sparktop" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "79dd0bf80fe79d7635bc83f7b3eda80947bb482b230e29e9c1d091b30c72ac04"
      url "https://github.com/galaxy-io/sparktop/releases/download/v#{version}/sparktop_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "04ba0615d83b5e4a35a28223130fb44b92e8d607e1ded4fcea32732931ef7240"
      url "https://github.com/galaxy-io/sparktop/releases/download/v#{version}/sparktop_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "238f8434f367e4412ff4e311abcac8029df68a130ee394aefb8590feaca1c968"
      url "https://github.com/galaxy-io/sparktop/releases/download/v#{version}/sparktop_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b3077cf7a3b5b8f8c8690b83e5f89ab791e0024378bd2169c69a3535347a6a5e"
      url "https://github.com/galaxy-io/sparktop/releases/download/v#{version}/sparktop_linux_amd64.tar.gz"
    end
  end

  name "sparktop"
  desc "DGX Spark TUI that takes the heat"
  homepage "https://github.com/galaxy-io/sparktop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sparktop"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sparktop"]
    end
  end

  # No zap stanza required
end
