# This file was generated by GoReleaser. DO NOT EDIT.
cask "tempo" do
  version "0.1.14"

  on_macos do
    on_arm do
      sha256 "fe28673a6f416ef0ab8a2c3861fb62ebe19b7e596ebc1a82f922c5d4417a561d"
      url "https://github.com/galaxy-io/tempo/releases/download/v#{version}/tempo_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ef94bd5911347e48b116099d181829249ecb6ca9af0550641e469a1e852d3b4d"
      url "https://github.com/galaxy-io/tempo/releases/download/v#{version}/tempo_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b6e14e26effaa0cf16376b30cd12aab9e430410ab66c9f5cdc28a14176dca131"
      url "https://github.com/galaxy-io/tempo/releases/download/v#{version}/tempo_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ac13f2e3c3c198df602f81fd09432e8d6dcb973044422763d1abe76a274640aa"
      url "https://github.com/galaxy-io/tempo/releases/download/v#{version}/tempo_linux_amd64.tar.gz"
    end
  end

  name "tempo"
  desc "Terminal UI for Temporal workflow management"
  homepage "https://github.com/galaxy-io/tempo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tempo"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/tempo"]
    end
  end

  # No zap stanza required
end
