# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Filament < Formula
  desc "Filament CLI"
  homepage "https://github.com/galaxy-io/filament"
  version "0.1.0-dev.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/galaxy-io/filament/releases/download/v0.1.0-dev.1/filament_darwin_amd64.tar.gz"
      sha256 "37502ba148e332ae21cc8572d6adbcfd250c8fd4bb36a53d0b19cccdc39ed3cd"

      define_method(:install) do
        bin.install "filament"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/galaxy-io/filament/releases/download/v0.1.0-dev.1/filament_darwin_arm64.tar.gz"
      sha256 "205bccf192013661d625d4500ee18061f87fd83f8894c9be3d70b0fa24d7ebe9"

      define_method(:install) do
        bin.install "filament"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/filament/releases/download/v0.1.0-dev.1/filament_linux_amd64.tar.gz"
      sha256 "900fd7a1063f72d3095f9db7a227c349a188794958ac8dbcfd9dc5a5ed7244c4"
      define_method(:install) do
        bin.install "filament"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/filament/releases/download/v0.1.0-dev.1/filament_linux_arm64.tar.gz"
      sha256 "87d1110a8e4930f8832e8a9116a4752dff3aa3de143be9412f127aee57b890e7"
      define_method(:install) do
        bin.install "filament"
      end
    end
  end

  test do
    system "#{bin}/filament", "version"
  end
end
