# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Filament < Formula
  desc "Filament CLI"
  homepage "https://github.com/galaxy-io/filament"
  version "0.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/galaxy-io/filament/releases/download/v0.4.1/filament_darwin_amd64.tar.gz"
      sha256 "8a68ad5bb00916076f3a42d610a0145edf5d8b6feaefcc74f3636326db6a59da"

      define_method(:install) do
        bin.install "filament"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/galaxy-io/filament/releases/download/v0.4.1/filament_darwin_arm64.tar.gz"
      sha256 "f8cbfa35144e35d774b18792d48cd6cd651ea41ffbbc8044abbef05aa68ebc38"

      define_method(:install) do
        bin.install "filament"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/filament/releases/download/v0.4.1/filament_linux_amd64.tar.gz"
      sha256 "b47bd82127d14ba098015be655461b151404f8286f6d96670df50d111e0dd66e"
      define_method(:install) do
        bin.install "filament"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/filament/releases/download/v0.4.1/filament_linux_arm64.tar.gz"
      sha256 "4333fe02a5e650a628a70771de3f9735f89074bdfd5eb7a91eedd65e6d17ab8f"
      define_method(:install) do
        bin.install "filament"
      end
    end
  end

  test do
    system "#{bin}/filament", "version"
  end
end
