# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gnat < Formula
  desc "Terminal UI for NATS JetStream management"
  homepage "https://github.com/galaxy-io/gnat"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/galaxy-io/gnat/releases/download/v0.1.5/gnat_darwin_amd64.tar.gz"
      sha256 "e83dfeec43e08194a650f63836bba1e6ce497ca509ab46f76ba7a3f54ac8986e"

      define_method(:install) do
        bin.install "gnat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/galaxy-io/gnat/releases/download/v0.1.5/gnat_darwin_arm64.tar.gz"
      sha256 "97c27678a1f8befe9143f25f4548d01df3a0783a4c364c6825653c7503b484a5"

      define_method(:install) do
        bin.install "gnat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/gnat/releases/download/v0.1.5/gnat_linux_amd64.tar.gz"
      sha256 "eb97a7da7ad343006b909de0f346e75c5bce5af135247c45236b49e2faed0d72"
      define_method(:install) do
        bin.install "gnat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/gnat/releases/download/v0.1.5/gnat_linux_arm64.tar.gz"
      sha256 "5aec942e7c0d1d7148d7a9e64b4b1011a622f150af46a3ee82047073c6662431"
      define_method(:install) do
        bin.install "gnat"
      end
    end
  end

  test do
    system "#{bin}/gnat", "--version"
  end
end
