# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gnat < Formula
  desc "TUI Client for NATS"
  homepage "https://github.com/galaxy-io/gnat"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/galaxy-io/gnat/releases/download/v0.1.8/gnat_darwin_amd64.tar.gz"
      sha256 "518534a02bb21085bdf1684f75d1051070cfae2f105926d5d9d50c60832a2fd9"

      define_method(:install) do
        bin.install "gnat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/galaxy-io/gnat/releases/download/v0.1.8/gnat_darwin_arm64.tar.gz"
      sha256 "41c2c4fcd290280ec3a85c00fc167927b664939225d5b9452cec91eb1dcff46c"

      define_method(:install) do
        bin.install "gnat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/gnat/releases/download/v0.1.8/gnat_linux_amd64.tar.gz"
      sha256 "7a255587f0f8bc11361579ea16cac60b6a0c017384d14df457b3a9c5d68e8d2d"
      define_method(:install) do
        bin.install "gnat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/gnat/releases/download/v0.1.8/gnat_linux_arm64.tar.gz"
      sha256 "41dcaed6515df7ab814648a96676aefc6b0c56ce7bb23af1488dac5b67934dfb"
      define_method(:install) do
        bin.install "gnat"
      end
    end
  end

  test do
    system "#{bin}/gnat", "--version"
  end
end
