# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sparktop < Formula
  desc "A DGX Spark TUI that takes the heat."
  homepage "https://github.com/galaxy-io/sparktop"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/galaxy-io/sparktop/releases/download/v0.1.1/sparktop_darwin_amd64.tar.gz"
      sha256 "f97a6bcb2b4bb4c1b466696238090c209b96f40b2521f872b15e282fea4ce20a"

      define_method(:install) do
        bin.install "sparktop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/galaxy-io/sparktop/releases/download/v0.1.1/sparktop_darwin_arm64.tar.gz"
      sha256 "4bd18a8c57baf4936cff69c6b6931b6ce4fdacc1cd9f953ae7dd2758e30736d2"

      define_method(:install) do
        bin.install "sparktop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/sparktop/releases/download/v0.1.1/sparktop_linux_amd64.tar.gz"
      sha256 "fbcb7c9973c1ea50fe991553dc43a33997d354451eb620b9043000f9c64320c3"
      define_method(:install) do
        bin.install "sparktop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/sparktop/releases/download/v0.1.1/sparktop_linux_arm64.tar.gz"
      sha256 "a97416e5f2998e8008f4f53be81a4bd5e7476fe699c941a47b5ec13b18028dec"
      define_method(:install) do
        bin.install "sparktop"
      end
    end
  end

  test do
    system "#{bin}/sparktop", "version"
  end
end
