# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sparktop < Formula
  desc "A DGX Spark TUI that takes the heat."
  homepage "https://github.com/galaxy-io/sparktop"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/galaxy-io/sparktop/releases/download/v0.1.0/sparktop_darwin_amd64.tar.gz"
      sha256 "a5c8625fb9328fb5a00646261001a28445ce2364ebcf8e468f946b7170d12f7d"

      define_method(:install) do
        bin.install "sparktop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/galaxy-io/sparktop/releases/download/v0.1.0/sparktop_darwin_arm64.tar.gz"
      sha256 "17d5b3ce13bd44777ed5d887441f405bbf4c1dd1b42576cc755e6e851f91d77c"

      define_method(:install) do
        bin.install "sparktop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/sparktop/releases/download/v0.1.0/sparktop_linux_amd64.tar.gz"
      sha256 "643e7ba2ef209fcf7e93fda4f4c14edf70207ce5f591c76d88f409b947c1e67e"
      define_method(:install) do
        bin.install "sparktop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/sparktop/releases/download/v0.1.0/sparktop_linux_arm64.tar.gz"
      sha256 "688e3907df2e2986d9a64e87556de1e0cd07aeca22a4faa75dd799384d0e9e6d"
      define_method(:install) do
        bin.install "sparktop"
      end
    end
  end

  test do
    system "#{bin}/sparktop", "version"
  end
end
