# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sparktop < Formula
  desc "DGX Spark TUI that takes the heat"
  homepage "https://github.com/galaxy-io/sparktop"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/galaxy-io/sparktop/releases/download/v0.1.2/sparktop_darwin_amd64.tar.gz"
      sha256 "04ba0615d83b5e4a35a28223130fb44b92e8d607e1ded4fcea32732931ef7240"

      define_method(:install) do
        bin.install "sparktop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/galaxy-io/sparktop/releases/download/v0.1.2/sparktop_darwin_arm64.tar.gz"
      sha256 "79dd0bf80fe79d7635bc83f7b3eda80947bb482b230e29e9c1d091b30c72ac04"

      define_method(:install) do
        bin.install "sparktop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/sparktop/releases/download/v0.1.2/sparktop_linux_amd64.tar.gz"
      sha256 "b3077cf7a3b5b8f8c8690b83e5f89ab791e0024378bd2169c69a3535347a6a5e"
      define_method(:install) do
        bin.install "sparktop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/sparktop/releases/download/v0.1.2/sparktop_linux_arm64.tar.gz"
      sha256 "238f8434f367e4412ff4e311abcac8029df68a130ee394aefb8590feaca1c968"
      define_method(:install) do
        bin.install "sparktop"
      end
    end
  end

  test do
    system "#{bin}/sparktop", "version"
  end
end
