# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tempo < Formula
  desc "Terminal UI for Temporal workflow management"
  homepage "https://github.com/galaxy-io/tempo"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/galaxy-io/tempo/releases/download/v0.1.1/tempo_darwin_amd64.tar.gz"
      sha256 "ddaa57f525a968ccb4e3dc16f43a6b68d71b6a8f8151449a9b67d965a3258dec"

      def install
        bin.install "tempo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/galaxy-io/tempo/releases/download/v0.1.1/tempo_darwin_arm64.tar.gz"
      sha256 "e9e02bf517443a394bf55c86ff8ba16b1d549271293d2069ef9fa9aa2a8a3463"

      def install
        bin.install "tempo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/tempo/releases/download/v0.1.1/tempo_linux_amd64.tar.gz"
      sha256 "e0d2f9f6778930b9229c44c35dab13d8f799ee6bc53a0caf0061323caa17575d"
      def install
        bin.install "tempo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/galaxy-io/tempo/releases/download/v0.1.1/tempo_linux_arm64.tar.gz"
      sha256 "b17664a9a26417f58779ecfc631c74326218d62e4ab1e9cda99d439414c085e8"
      def install
        bin.install "tempo"
      end
    end
  end

  test do
    system "#{bin}/tempo", "--version"
  end
end
